---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: node1-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     worker: node1
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 64505
   exportPodCIDR: false
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.237.0.253/32'
      peerASN: 64503
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
   serviceSelector:
      matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: node2-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     worker: node2
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 64506
   exportPodCIDR: false
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.237.0.253/32'
      peerASN: 64504
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
   serviceSelector:
      matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: node3-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     worker: node3
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 64505
   exportPodCIDR: false
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.237.0.253/32'
      peerASN: 64503
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
   serviceSelector:
      matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']}
