# cluster.yaml
kind: Cluster
name: clab2-k8s
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true 
  podSubnet: "10.2.0.0/16"
  serviceSubnet: "10.3.0.0/16"
  #podSubnet: "10.12.0.0/16"
  #apiServerPort: 6433
  kubeProxyMode: "none"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.237.0.2  

- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.237.0.3
        node-labels: "worker=rack0"    

- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.237.0.4
        node-labels: "worker=rack0"    

- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-ip: 10.237.0.5
        node-labels: "worker=rack0"  
