apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: worker-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     pool: worker
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 64504
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.227.0.254/24'
      peerASN: 64502
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
   serviceSelector:
     matchExpressions:
     - key: somekey
       operator: NotIn
       values:
       - never-used-value
